title: DataGrupo
description: Grupo de análise de dados, todos os dados.
author: datagrupo
logo: 
github: https://github.com/datagrupo
about: Análise de dados, todos os dados

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: datagrupo
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
